apiVersion: v1
kind: # jaki rodzaj ?
metadata:
  name: # name ?
  namespace: app
  labels:
    app: # name ?
spec:
  type: # jaki rodzaj musi być aby serwis nadzorował obciążenie ?
  selector:
    app: # name ?
  ports:
    - name: http
      port: # port ?
      targetPort: # port kontenera ?
      protocol: TCP